name: Publish film-vue-app
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Vue
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
#  build_vue:
#    runs-on: ubuntu-latest
#    name: Build Vue
#    steps:
#      - uses: actions/checkout@v3
#      - id: Build-Vue

